- name: Set hostname in /etc/hostname
  copy:
    content: "{{ hostname_hostname }}\n"
    dest: /etc/hostname

- name: Set hostnames in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
  loop:
    - { line: "127.0.0.1\tlocalhost\t{{ hostname_hostname }}", regexp: '^[\.0127]*\tlocalhost\t.*$' }
    - { line: "::1\t\tlocalhost\t{{ hostname_hostname }}", regexp: '^::1\t\tlocalhost\t.*$' }
