---
- name: Install arch
  hosts:
    - remote_system
  tags:
    - bootstrap
  pre_tasks:
    - import_role:
        name: bootstrap/check
  roles:
    - bootstrap/disksetup
    - bootstrap/configure
    - bootstrap/user
  post_tasks:
    - name: Reboot into the system
      tags: reboot
      reboot:
        reboot_timeout: 120
        connect_timeout: 10

- name: Main setup
  hosts:
    - remote_system
  tags:
    - mainsetup
  pre_tasks:
    - import_role:
        name: mainsetup/setup
  roles:
    - mainsetup/system
    - mainsetup/dotfiles
    - mainsetup/apps
    - mainsetup/x11
  post_tasks:
    - name: Reboot into the system
      tags: reboot
      reboot:
        reboot_timeout: 120
        connect_timeout: 10
