---
- name: Install arch
  hosts:
    - vm
  tags:
    - bootstrap
  pre_tasks:
    - import_role:
        name: check
  roles:
    - disksetup
    - configure
    - user
  post_tasks:
   - name: Reboot into the system
     tags: reboot
     reboot:

- name: Dotfiles install
  hosts:
    - vm
  tags:
    - mainsetup
  pre_tasks:
    - import_role:
        name: setup
  roles:
    - hostname
    - locales
    - dotfiles
    - apps
    - x11
  post_tasks:
    - name: Reboot into the system
      tags: reboot
      reboot:
