- name: Allow admins to sudo by authorizing the wheel group
  lineinfile:
    path: "{{ mount_path }}/etc/sudoers"
    regexp: "^# %wheel ALL=\\(ALL:ALL\\) ALL"
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: 'visudo -cf %s'

- name: Ask for username
  pause:
    prompt: "Enter username: "
    echo: yes
  register: username

- name: Check that the user is present
  shell: cat {{ mount_path }}/etc/passwd | grep {{ username.user_input }}
  register: user_exists

- name: Ask for password
  pause:
    prompt: "Enter password: "
    echo: no
  register: password
  when: user_exists.stdout_lines | length == 0

- name: Create user account
  block:
  - name: Create user account
    command: arch-chroot {{ mount_path }} useradd -m -g users -G wheel -s /bin/bash "{{ username.user_input }}"
  - name: Set the user account password
    command: arch-chroot {{ mount_path }} usermod --password "{{ password.user_input | password_hash('sha512') }}" "{{ username.user_input }}"
  tags: add_user
  when: user_exists.stdout_lines | length == 0
