- name: Allow admins to sudo by authorizing the wheel group
  lineinfile:
    path: "{{ mount_path | quote }}/etc/sudoers"
    regexp: "^# %wheel ALL=\\(ALL:ALL\\) ALL"
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: 'visudo -cf %s'

- name: Check that the user is present
  shell: cat {{ mount_path | quote }}/etc/passwd | sed -n "/^{{ username }}/p"
  register: user_exists

- name: Create user account
  block:
  - name: Create user account
    command: arch-chroot {{ mount_path | quote }} useradd -m -g users -G wheel -s /bin/bash "{{ username }}"
  - name: Set the user account password
    command: arch-chroot {{ mount_path | quote }} usermod --password "{{ user_pass | password_hash('sha512') }}" "{{ username }}"
  tags: add_user
  when: user_exists.stdout_lines | length == 0
