packages_list:
  - pipewire            # Core
  - pipewire-alsa       # ALSA compatibility
  - pipewire-pulse      # PulseAudio replacement (drop-in)
  - wireplumber         # Session manager - required
  - pavucontrol         # GUI volume mixer
  # - pipewire-jack     # only for audio production (JACK compatibility)
