- name: Generate fstab
  shell: genfstab -U {{ mount_path }} > "{{ mount_path }}/etc/fstab"
  changed_when: true

- name: Replace udev with systemd hook for sd-encrypt compatibility
  lineinfile:
    path: "{{ mount_path }}/etc/mkinitcpio.conf"
    backrefs: yes
    regexp: '^(HOOKS=.*)\budev\b(.*)'
    line: '\1systemd\2'

- name: Check if custom hooks are already present
  lineinfile:
    path: "{{ mount_path }}/etc/mkinitcpio.conf"
    regexp: '^HOOKS=\((?=.*{{ hooks | join(")(?=.*") }}).*\)'
    state: absent
  check_mode: true
  register: hooks_already_present

- name: Add additional hooks to mkinitcpio config
  lineinfile:
    path: "{{ mount_path }}/etc/mkinitcpio.conf"
    backrefs: yes
    regexp: '^HOOKS=\((.*)\bfilesystems\b(.*)\)'
    line: 'HOOKS=(\1{{ hooks | join(" ") }} filesystems\2)'
  when: not (hooks_already_present.found | default(false))

- name: Set language
  template:
    src: vconsole.conf.j2
    dest: "{{ mount_path }}/etc/vconsole.conf"

- name: Regenerate initramfs
  command: arch-chroot {{ mount_path }} mkinitcpio -P
