- listen: Delete passwordless sudo user
  name: Remove passwordless sudo user from sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^{{ passwordless_sudo_user_name | regex_escape }} ALL=\\(ALL\\) NOPASSWD: ALL$"
    validate: '/usr/sbin/visudo -cf %s'

- listen: Delete passwordless sudo user
  name: Delete a user that can use passwordless sudo
  user:
    name: "{{ passwordless_sudo_user_name }}"
    state: absent
    remove: yes
