install_drive: /dev/nvme0n1
luksdevice_name: luks_lvm
boot_partition_suffix: "p1"
crypt_partition_suffix: "p2"
bootdevice: "{{ install_drive }}{{ boot_partition_suffix }}"
cryptdevice: "{{ install_drive }}{{ crypt_partition_suffix }}"
volumegroupname: "arch"
logicalvolumename_root: "root"
logicalvolumename_swap: "swap"
mount_path: "/mnt"
