- import_role:
    name: installer
  vars:
    packages: "{{ packages_list }}"
    task_name: betterlockscreen
- name: Enable betterlockscreen service for suspend/sleep
  systemd:
    name: "betterlockscreen@{{ username }}"
    enabled: true
  become: true
