- name: Install batch of packages for '{{ task_name | default("") }}'-task
  become: true
  become_user: "{{ passwordless_sudo_user_name }}"
  command: >
    yay -S
      --answerclean none --answeredit none --answerupgrade none --answerdiff none
      --removemake --noconfirm --combinedupgrade --needed {{ item | quote }}
  loop: "{{ packages_list }}"

