- import_role:
    name: mainsetup/installer
  vars:
    packages: "{{ packages_list }}"
    task_name: zram

- name: Deploy zram-generator config
  become: true
  copy:
    src: zram-generator.conf
    dest: /etc/systemd/zram-generator.conf
    owner: root
    group: root
    mode: "0644"

- name: Deploy sysctl config for ZRAM
  become: true
  copy:
    src: 99-zram.conf
    dest: /etc/sysctl.d/99-zram.conf
    owner: root
    group: root
    mode: "0644"
