- include_role:
    name: "disksetup/partitioning"
    public: yes
- import_role:
    name: base_packages
- include_role:
    name: "disksetup/postpartitioning"
    public: yes
- include_role:
    name: "disksetup/bootloader"
    public: yes
