- name: Create a user that can use passwordless sudo
  user:
    name: "{{ passwordless_sudo_user_name }}"
    shell: /bin/bash
    password: "!"
    system: yes
  notify: Delete passwordless sudo user
  changed_when: yes

- name: Add passwordless sudo user to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ passwordless_sudo_user_name | regex_escape }} "
    line: "{{ passwordless_sudo_user_name }} ALL=(ALL) NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'
