- import_role:
    name: "apps/base"
- import_role:
    name: "apps/audio"
- import_role:
    name: "apps/thunar"
- import_role:
    name: "apps/bluetooth"
- import_role:
    name: "apps/docker"
- import_role:
    name: "apps/qtile"
- import_role:
    name: "apps/vim"
- import_role:
    name: "apps/zsh"
- import_role:
    name: "apps/yazi"
- import_role:
    name: "apps/betterlockscreen"
