- name: Upgrade packages
  pacman:
    update_cache: true
    upgrade: true
- name: Install git
  pacman:
    name: git
    state: present
- name: Copy backlight udev rule
  copy:
    src: 90-backlight.rules
    dest: /etc/udev/rules.d/90-backlight.rules
    owner: root
    group: root
    mode: "0644"
  notify: Reload udev rules
- name: Install monitor hotplug udev rule
  template:
    src: 95-monitor-hotplug.rules.j2
    dest: /etc/udev/rules.d/95-monitor-hotplug.rules
    owner: root
    group: root
    mode: "0644"
  notify: Reload udev rules
