- name: Upgrade packages
  pacman:
    update_cache: true
    upgrade: true
- name: Install git
  pacman:
    name: git
    state: present
- name: Copy backlight-udev rule
  copy:
    src: backlight.rules
    dest: /etc/udev/rules.d/
