- name: Install archlinux-keyring via pacman
  pacman:
    name: archlinux-keyring
    state: latest
    update_cache: true
- name: Run pacstrap
  command: >
    pacstrap {{ mount_path | quote }} --needed
    {% for pkg in base_packages %}
      {{ pkg | quote }}
    {% endfor %}
